# Generated by Django 2.2.16 on 2020-10-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerproperties',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
